-- Add selective liberal arts schools to the schools table
INSERT INTO public.schools (name, domain_whitelist, status) VALUES
  ('Bowdoin College', ARRAY['bowdoin.edu'], 'active'),
  ('University of Edinburgh', ARRAY['ed.ac.uk'], 'active'),
  ('Amherst College', ARRAY['amherst.edu'], 'active'),
  ('Williams College', ARRAY['williams.edu'], 'active'),
  ('Colgate University', ARRAY['colgate.edu'], 'active'),
  ('Colby College', ARRAY['colby.edu'], 'active'),
  ('Middlebury College', ARRAY['middlebury.edu'], 'active'),
  ('Bates College', ARRAY['bates.edu'], 'active'),
  ('Hamilton College', ARRAY['hamilton.edu'], 'active'),
  ('Trinity College', ARRAY['trincoll.edu'], 'active'),
  ('Skidmore College', ARRAY['skidmore.edu'], 'active'),
  ('Wesleyan University', ARRAY['wesleyan.edu'], 'active'),
  ('Connecticut College', ARRAY['conncoll.edu'], 'active'),
  ('Kenyon College', ARRAY['kenyon.edu'], 'active'),
  ('Oberlin College', ARRAY['oberlin.edu'], 'active'),
  ('Macalester College', ARRAY['macalester.edu'], 'active'),
  ('St. Olaf College', ARRAY['stolaf.edu'], 'active'),
  ('Grinnell College', ARRAY['grinnell.edu'], 'active'),
  ('Franklin & Marshall College', ARRAY['fandm.edu'], 'active'),
  ('Dickinson College', ARRAY['dickinson.edu'], 'active'),
  ('Denison University', ARRAY['denison.edu'], 'active'),
  ('Occidental College', ARRAY['oxy.edu'], 'active'),
  ('Whitman College', ARRAY['whitman.edu'], 'active'),
  ('Reed College', ARRAY['reed.edu'], 'active');